# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MagentaA11y
title-aria-label: Magenta Ally
email:
description: >- # this means to ignore newlines until "baseurl:"
  The accessibility acceptance criteria testing checklist generator by T-Mobile - Accessibility Resource Center
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.magentaa11y.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
google_analytics: UA-1659086-24
# Build settings
theme: minima
plugins:
- jekyll-feed
collections:
  checklist-web:
    output: true
    permalink: /:collection/:name/
  checklist-native:
    output: true
    permalink: /:collection/:name/
  demos:
    output: true
    permalink: /:collection/:name/
web-categories-order:
- html
- header
- nav
- main
- form
- footer
native-categories-order:
- controls
- notifications
- patterns
video-demos:
- title: iOS Voiceover
  directory: ios/
- title: Android Talkback
  directory: android/
- title: Windows Jaws Chrome
  directory: jaws/
- title: Windows NVDA Chrome
  directory: nvda/
- title: MacOS Voiceover Safari
  directory: macos/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/